/**
 * The assistant's grounded answer tier.
 *
 * Every answer here is composed at build time from the committed Gate 9
 * record. Nothing is fetched, nothing is generated, and nothing can be
 * invented — which is precisely why this tier is also the fallback when a
 * future model tier is unavailable, rate limited, or returns output that
 * fails citation validation.
 *
 * Because it ships in the client bundle, it keeps working with the backend
 * entirely down. That is the point: the assistant degrades to something
 * truthful rather than to a spinner.
 */
import { managerAnswers, resolveManagerAnswer, type ManagerAnswer } from "../organisation/managerAnswers";

/** Where an answer came from. The UI must always show this to the reader. */
export type AnswerProvenance =
  /** Composed from the sealed record at build time. No model involved. */
  | "sealed-record"
  /** Generated by a model and validated against retrieved evidence. */
  | "model-cited";

export type GroundedAnswer = {
  id: string;
  question: string;
  answer: string;
  source: string;
  provenance: AnswerProvenance;
};

export type AssistantReply =
  | { status: "answered"; answer: GroundedAnswer }
  | { status: "unmatched"; notice: string };

/** The starter questions offered as chips, in the order they are shown. */
export const suggestedQuestions: readonly GroundedAnswer[] = managerAnswers.map(toGroundedAnswer);

function toGroundedAnswer(entry: ManagerAnswer): GroundedAnswer {
  return {
    id: entry.id,
    question: entry.question,
    answer: entry.answer,
    source: entry.source,
    provenance: "sealed-record",
  };
}

/**
 * Resolve free text against the sealed record.
 *
 * Deliberately returns an explicit `unmatched` rather than a best-effort
 * paragraph: an assistant that guesses is worse than one that says it cannot
 * answer, and the honest notice is what the reader sees.
 */
export function answerFromSealedRecord(input: string): AssistantReply {
  const { answer, notice } = resolveManagerAnswer(input);

  if (!answer) {
    return { status: "unmatched", notice };
  }

  return { status: "answered", answer: toGroundedAnswer(answer) };
}
